services:
  web:
    build: .
    image: backend-image:latest
    ports:
      - "8080:8080"
    networks:
      project-bridge:
        - aliases:
            - backend

networks:
  project-bridge:
    name: project-bridge
    driver: bridge